dist: trusty
sudo: false
language: python
cache: pip

branches:
  only:
    - master

install:
  - pip install -e .

script:
  - make build

matrix:
  include:
    - python: 2.7

deploy:
  provider: pypi
  user:
    secure: TODO
  password:
    secure: TODO
  distributions: "sdist bdist_wheel"
  on:
    tags: true

notifications:
  email:
    on_success: never
