name: GitHub CI
on: [push]

jobs:
  test:
    name: test suite on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04]
    steps:
    - name: test and build
      run: |
        python2.7 -m pip install -e ".[test]"
        make build
